### A simple get request to the test endpoint. No need for login
GET {{url}}/auth/test/

### Populate the database with some data
POST {{url}}/todos/populate/

### Create a new user - this one will only get a USER role by default
POST {{url}}/auth/register/

{
    "username": "user",
    "password": "test123"
}

###
POST {{url}}/auth/login/

{
    "username": "user",
    "password": "test123"
}

> {%
    client.global.set("jwt_token", response.body.token);
    console.log("JWT Token:", client.global.get("jwt_token"));
%}

###
GET {{url}}/protected/user_demo/
Accept: application/json
Authorization: Bearer {{jwt_token}}

###
GET {{url}}/protected/admin_demo/
Accept: application/json
Authorization: Bearer {{jwt_token}}

### Add admin role to user
POST {{url}}/auth/user/addrole/
Accept: application/json
Authorization: Bearer {{jwt_token}}

{
    "role": "admin"
}
Accept: application/json
Authorization: Bearer {{jwt_token}}

### Populate the database with orders
POST {{url}}/orders/populate
Content-Type: application/json

### Create a new order
POST {{url}}/orders
Content-Type: application/json
Authorization: Bearer {{jwt_token}}

{
  "orderPrice": 25.99,
  "orderDate": "2023-10-01",
  "user": {
    "username": "user"
  },
  "orderLines": [
    {
      "pizza": {
        "id": 1
      },
      "quantity": 2
    }
  ]
}

### Get all orders
GET {{url}}/orders
Accept: application/json
Authorization: Bearer {{jwt_token}}

### Get a specific order by ID
GET {{url}}/orders/1
Accept: application/json
Authorization: Bearer {{jwt_token}}

### Get all orders for the current user
GET {{url}}/orders/user
Accept: application/json
Authorization: Bearer {{jwt_token}}

### Update an order by ID
PUT {{url}}/orders/{id}
Content-Type: application/json
Authorization: Bearer {{jwt_token}}

{
  "orderPrice": 30.99,
  "orderDate": "2023-10-02",
  "user": {
    "username": "user"
  },
  "orderLines": [
    {
      "pizza": {
        "id": 1
      },
      "quantity": 3
    }
  ]
}

### Delete an order by ID
DELETE {{url}}/orders/{id}
Authorization: Bearer {{jwt_token}}