### Populate the database with pizzas
POST {{url}}/pizzas/populate
Content-Type: application/json


### Create a new pizza
POST {{url}}/pizzas
Content-Type: application/json
Authorization: Bearer {{jwt_token}}

{
  "name": "Veggie",
  "description": "Delicious veggie pizza",
  "toppings": "Tomato, mozzarella, bell peppers, onions, olives",
  "price": 10.99,
  "pizzaType": "REGULAR"
}

### Get all pizzas
GET {{url}}/pizzas

### Get a specific pizza by ID
GET {{url}}/pizzas/1

### Get all pizzas for the current user
GET {{url}}/pizzas/user

### Update a pizza by ID
PUT {{url}}/pizzas/1
Content-Type: application/json

{
  "name": "Updated Veggie",
  "description": "Updated delicious veggie pizza",
  "toppings": "Tomato, mozzarella, bell peppers, onions, olives, mushrooms",
  "price": 11.99,
  "pizzaType": "REGULAR"
}

### Delete a pizza by ID
DELETE {{url}}/pizzas/1


### A simple get request to the test endpoint. No need for login
GET {{url}}/auth/test/

### Populate the database with some data
POST {{url}}/todos/populate/

### Create a new user - this one will only get a USER role by default
POST {{url}}/auth/register/

{
    "username": "user",
    "password": "test123"
}

###
POST {{url}}/auth/login/

{
    "username": "user",
    "password": "test123"
}

> {%
    client.global.set("jwt_token", response.body.token);
    console.log("JWT Token:", client.global.get("jwt_token"));
%}

###
GET {{url}}/protected/user_demo/
Accept: application/json
Authorization: Bearer {{jwt_token}}

###
GET {{url}}/protected/admin_demo/
Accept: application/json
Authorization: Bearer {{jwt_token}}

### Add admin role to user
POST {{url}}/auth/user/addrole/
Accept: application/json
Authorization: Bearer {{jwt_token}}

{
    "role": "admin"
}
Accept: application/json
Authorization: Bearer {{jwt_token}}


### Populate the database with some pizzas
POST {{url}}/pizzas/populate/
Accept: application/json

### Create a new pizza
POST {{url}}/pizzas/
Content-Type: application/json
Authorization: Bearer {{jwt_token}}

{
  "name": "Hawaiian",
  "description": "Pizza with ham and pineapple",
  "toppings": "Ham, Pineapple",
  "price": 13.99,
  "pizzaType": "REGULAR"
}


### Get all pizzas
GET {{url}}/pizzas/
Accept: application/json

### Get all pizzas for the logged-in user
GET {{url}}/pizzas/mine
Accept: application/json
Authorization: Bearer {{jwt_token}}

### Get a specific pizza by ID
GET {{url}}/pizzas/1
Accept: application/json
Authorization: Bearer {{jwt_token}}

### Update a specific pizza by ID
PUT {{url}}/pizzas/1
Content-Type: application/json
Authorization: Bearer {{jwt_token}}

{
  "name": "Updated Hawaiian",
  "description": "Pizza with ham, pineapple, and extra cheese",
  "toppings": "Ham, Pineapple, Extra Cheese",
  "price": 14.99,
  "pizzaType": "REGULAR"
}

### Delete a specific pizza by ID
DELETE {{url}}/pizzas/1
Authorization: Bearer {{jwt_token}}